const users = [
    {
        id: 1,
        name: "Lungile Dlamini",
        email: "lungile.dlamini@example.com",
        password: "hashed_password_1",
        age: 28,
        location: "Durban, South Africa",
        userType: "artist",
        genrePreference: ["Amapiano", "Afro House"],
        artistType: "Solo",
        profileComplete: true,
        submittedTracks: ["Dreams of Durban", "Afro Sunrise"],
        nftEligibleTracks: ["Dreams of Durban"],
        joinedDate: "2025-01-01",
    },
    {
        id: 2,
        name: "Sipho Mkhize",
        email: "sipho.mkhize@example.com",
        password: "hashed_password_2",
        age: 34,
        location: "Johannesburg, South Africa",
        userType: "investor",
        genrePreference: ["Deep House", "Afro Soul"],
        investments: [1],
        joinedDate: "2025-01-02",
    },
    {
        id: 3,
        name: "Thandi Ngcobo",
        email: "thandi.ngcobo@example.com",
        password: "hashed_password_3",
        age: 25,
        location: "Cape Town, South Africa",
        userType: "supplier",
        servicesOffered: ["Marketing", "Social Media Promotion"],
        jobsCompleted: ["Job 1"],
        joinedDate: "2025-01-03",
    },
    {
        id: 4,
        name: "Kabelo Mokoena",
        email: "kabelo.mokoena@example.com",
        password: "hashed_password_4",
        age: 31,
        location: "Pretoria, South Africa",
        userType: "artist",
        genrePreference: ["Hip Hop", "Rap"],
        artistType: "Band",
        profileComplete: false,
        submittedTracks: [],
        nftEligibleTracks: [],
        joinedDate: "2025-01-04",
    },
    {
        id: 5,
        name: "Zanele Khumalo",
        email: "zanele.khumalo@example.com",
        password: "hashed_password_5",
        age: 29,
        location: "Bloemfontein, South Africa",
        userType: "admin",
        permissions: ["manageUsers", "reviewTracks", "approveNFTs"],
        joinedDate: "2025-01-05",
    },
    // Additional Users
    {
        id: 6,
        name: "Tsepo Mogale",
        email: "tsepo.mogale@example.com",
        password: "hashed_password_6",
        age: 22,
        location: "Soweto, South Africa",
        userType: "artist",
        genrePreference: ["Afro-Pop"],
        artistType: "Solo",
        profileComplete: true,
        submittedTracks: ["Soweto Blues"],
        nftEligibleTracks: ["Soweto Blues"],
        joinedDate: "2025-01-06",
    },
    {
        id: 7,
        name: "Amanda Ncube",
        email: "amanda.ncube@example.com",
        password: "hashed_password_7",
        age: 35,
        location: "Polokwane, South Africa",
        userType: "investor",
        genrePreference: ["Gospel", "Soul"],
        investments: [2],
        joinedDate: "2025-01-07",
    },
    {
        id: 8,
        name: "Bongani Khumalo",
        email: "bongani.khumalo@example.com",
        password: "hashed_password_8",
        age: 26,
        location: "Pietermaritzburg, South Africa",
        userType: "supplier",
        servicesOffered: ["Video Production"],
        jobsCompleted: ["Job 2"],
        joinedDate: "2025-01-08",
    },
    {
        id: 9,
        name: "Lerato Seoka",
        email: "lerato.seoka@example.com",
        password: "hashed_password_9",
        age: 30,
        location: "Kimberley, South Africa",
        userType: "artist",
        genrePreference: ["Neo-Soul", "Jazz"],
        artistType: "Solo",
        profileComplete: true,
        submittedTracks: ["Midnight Groove"],
        nftEligibleTracks: [],
        joinedDate: "2025-01-09",
    },
    {
        id: 10,
        name: "Sizwe Masondo",
        email: "sizwe.masondo@example.com",
        password: "hashed_password_10",
        age: 27,
        location: "East London, South Africa",
        userType: "investor",
        genrePreference: ["Reggae", "Hip Hop"],
        investments: [3, 5],
        joinedDate: "2025-01-10",
    },
    {
        id: 11,
        name: "Noluthando Mthembu",
        email: "noluthando.mthembu@example.com",
        password: "hashed_password_11",
        age: 21,
        location: "Gqeberha, South Africa",
        userType: "artist",
        genrePreference: ["Afro-Soul"],
        artistType: "Solo",
        profileComplete: false,
        submittedTracks: [],
        nftEligibleTracks: [],
        joinedDate: "2025-01-11",
    },
    {
        id: 12,
        name: "Linda Molefe",
        email: "linda.molefe@example.com",
        password: "hashed_password_12",
        age: 33,
        location: "Welkom, South Africa",
        userType: "supplier",
        servicesOffered: ["Brand Development", "PR"],
        jobsCompleted: ["Job 3", "Job 4"],
        joinedDate: "2025-01-12",
    },
    {
        id: 13,
        name: "Mandla Mkhize",
        email: "mandla.mkhize@example.com",
        password: "hashed_password_13",
        age: 24,
        location: "Richards Bay, South Africa",
        userType: "artist",
        genrePreference: ["House Music", "Kwaito"],
        artistType: "Duo",
        profileComplete: true,
        submittedTracks: ["Ocean Vibes", "Zulu Groove"],
        nftEligibleTracks: ["Ocean Vibes"],
        joinedDate: "2025-01-13",
    },
    {
        id: 14,
        name: "Tshepo Mabasa",
        email: "tshepo.mabasa@example.com",
        password: "hashed_password_14",
        age: 32,
        location: "Rustenburg, South Africa",
        userType: "admin",
        permissions: ["manageUsers", "approveNFTs"],
        joinedDate: "2025-01-14",
    },
    {
        id: 15,
        name: "Nonhlanhla Ndlovu",
        email: "nonhlanhla.ndlovu@example.com",
        password: "hashed_password_15",
        age: 28,
        location: "Mbombela, South Africa",
        userType: "artist",
        genrePreference: ["Afro-Pop"],
        artistType: "Band",
        profileComplete: true,
        submittedTracks: ["Lowveld Serenade"],
        nftEligibleTracks: [],
        joinedDate: "2025-01-15",
    },
    {
        id: 16,
        name: "Nkosinathi Mthethwa",
        email: "nkosinathi.mthethwa@example.com",
        password: "hashed_password_16",
        age: 39,
        location: "Durban, South Africa",
        userType: "investor",
        genrePreference: ["Jazz"],
        investments: [],
        joinedDate: "2025-01-16",
    },
    {
        id: 17,
        name: "Sibusiso Dladla",
        email: "sibusiso.dladla@example.com",
        password: "hashed_password_17",
        age: 36,
        location: "Johannesburg, South Africa",
        userType: "supplier",
        servicesOffered: ["Distribution"],
        jobsCompleted: ["Job 5", "Job 6"],
        joinedDate: "2025-01-17",
    },
    {
        id: 18,
        name: "Bongeka Gwala",
        email: "bongeka.gwala@example.com",
        password: "hashed_password_18",
        age: 26,
        location: "Cape Town, South Africa",
        userType: "artist",
        genrePreference: ["Amapiano"],
        artistType: "Solo",
        profileComplete: false,
        submittedTracks: [],
        nftEligibleTracks: [],
        joinedDate: "2025-01-18",
    },
    {
        id: 19,
        name: "Precious Mahlangu",
        email: "precious.mahlangu@example.com",
        password: "hashed_password_19",
        age: 23,
        location: "Tzaneen, South Africa",
        userType: "artist",
        genrePreference: ["Afro-Pop", "Traditional"],
        artistType: "Solo",
        profileComplete: true,
        submittedTracks: ["Heritage Groove"],
        nftEligibleTracks: [],
        joinedDate: "2025-01-19",
    },
    {
        id: 20,
        name: "Gugu Khuzwayo",
        email: "gugu.khuzwayo@example.com",
        password: "hashed_password_20",
        age: 29,
        location: "Sandton, South Africa",
        userType: "investor",
        genrePreference: ["Pop", "Amapiano"],
        investments: [4],
        joinedDate: "2025-01-20",
    },
];


const musicReviews = [
    {
        id: 1,
        userId: 1,
        artist: "Thando Sithole",
        album: "Dreams of Durban",
        song: "Golden Waves",
        rating: 4.5,
        review: "This track captures the vibrant spirit of Durban. The Afro-house vibe is infectious and feels authentic.",
    },
    {
        id: 2,
        userId: 2,
        artist: "Lwazi Ntuli",
        album: "Afro Sunrise",
        song: "Morning Glow",
        rating: 4.8,
        review: "A true masterpiece! The mix of Afro-pop and soulful lyrics makes it a standout on any playlist.",
    },
    {
        id: 3,
        userId: 3,
        artist: "Sihle Dlamini",
        album: "Gqom Beats Unleashed",
        song: "Midnight Stomp",
        rating: 3.9,
        review: "High-energy beats perfect for a party, though some tracks feel repetitive.",
    },
    {
        id: 4,
        userId: 4,
        artist: "Zama Mhlongo",
        album: "Midnight Groove",
        song: "Soulful Nights",
        rating: 4.2,
        review: "Smooth neo-soul with jazzy undertones. A refreshing take on South African music.",
    },
    {
        id: 5,
        userId: 5,
        artist: "Nandi Zulu",
        album: "Ocean Vibes",
        song: "Shoreline Dreams",
        rating: 4.7,
        review: "A beautiful blend of house music and coastal inspiration. Perfect for a relaxed evening.",
    },
    {
        id: 6,
        userId: 6,
        artist: "Jabu Khumalo",
        album: "Soweto Blues",
        song: "Freedom Echo",
        rating: 4.3,
        review: "Deeply moving. The saxophone on this track is pure magic.",
    },
    {
        id: 7,
        userId: 7,
        artist: "Linda Ndlovu",
        album: "Heritage Groove",
        song: "Ubuntu Anthem",
        rating: 4.0,
        review: "A unique fusion of traditional sounds with modern Afro-pop elements.",
    },
    {
        id: 8,
        userId: 8,
        artist: "The Zulu Kings",
        album: "Zulu Groove",
        song: "Warrior’s Dance",
        rating: 4.5,
        review: "Incredible percussion and vocal harmonies. A celebration of culture.",
    },
    {
        id: 9,
        userId: 9,
        artist: "Bongiwe Mbatha",
        album: "Lowveld Serenade",
        song: "Valley Whisper",
        rating: 4.1,
        review: "Relaxing and soulful. The acoustic guitar work is a standout.",
    },
    {
        id: 10,
        userId: 10,
        artist: "Siphesihle Gwala",
        album: "Tsonga Nights",
        song: "Dance in the Moonlight",
        rating: 3.8,
        review: "High-energy dance tracks that capture the nightlife vibes of Tsonga culture.",
    },
    {
        id: 11,
        userId: 11,
        artist: "Kabelo Phiri",
        album: "Dreamcatcher",
        song: "Chasing Stars",
        rating: 4.4,
        review: "An ethereal journey through soundscapes. Kabelo has a unique style.",
    },
    {
        id: 12,
        userId: 12,
        artist: "Zodwa Maduna",
        album: "Golden Strings",
        song: "Harmony’s Touch",
        rating: 4.6,
        review: "A gorgeous instrumental album with African string influences. Highly recommended.",
    },
    {
        id: 13,
        userId: 13,
        artist: "Lerato Mokoena",
        album: "Fire Within",
        song: "Burning Desire",
        rating: 4.9,
        review: "Powerful and emotive vocals with a strong gospel influence.",
    },
    {
        id: 14,
        userId: 14,
        artist: "Nokuthula Xaba",
        album: "Soul Reflection",
        song: "Inner Light",
        rating: 4.2,
        review: "Deep and introspective lyrics paired with smooth, jazzy instrumentals.",
    },
    {
        id: 15,
        userId: 15,
        artist: "Vusi Mahlangu",
        album: "Heart of the Beat",
        song: "Pulse of Africa",
        rating: 4.7,
        review: "An energetic album with an Amapiano twist that never fails to get you moving.",
    },
    {
        id: 16,
        userId: 16,
        artist: "Nomsa Khuzwayo",
        album: "Melody of Dreams",
        song: "Hopeful Sunrise",
        rating: 4.0,
        review: "A delightful Afro-soul album filled with hope and positivity.",
    },
    {
        id: 17,
        userId: 17,
        artist: "Siphiwe Ncube",
        album: "Kwaito Classics",
        song: "Street Anthem",
        rating: 4.3,
        review: "Nostalgic and energetic. A love letter to the Kwaito scene of the 2000s.",
    },
    {
        id: 18,
        userId: 18,
        artist: "Themba Nkosi",
        album: "City Lights",
        song: "Urban Dreams",
        rating: 3.9,
        review: "Catchy hooks and groovy beats, but some tracks lack depth.",
    },
    {
        id: 19,
        userId: 19,
        artist: "Ayanda Dlamini",
        album: "Morning Dew",
        song: "First Light",
        rating: 4.8,
        review: "Soothing vocals and lush harmonies. Perfect for a calm start to the day.",
    },
    {
        id: 20,
        userId: 20,
        artist: "Nkosi Mbatha",
        album: "Rise Up",
        song: "Together We Stand",
        rating: 4.6,
        review: "An uplifting Afro-pop album with strong vocal performances.",
    },
];

const mockSignUpUser = {
    name: "Zama Khumalo",
    email: "zama.khumalo@example.com",
    password: "SecurePassword123!", // To be hashed during processing
    age: 27,
    location: "Durban, South Africa",
    userType: "artist", // Possible values: "artist", "investor", "supplier"
    profileCompleted: false, // Indicates if the user has completed their profile
};


  
exports.users = users;
exports.musicReviews = musicReviews;
exports.mockSignUpUser = mockSignUpUser;
